apiVersion: apps/v1
kind: Deployment
metadata:
  name: pallete
  labels:
    app: pallete
spec:
  selector:
    matchLabels:
      app: pallete
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pallete
    spec:
      containers:
      - name: pallete
        image: 10.33.109.242/dummy/pallete:latest
        ports:
        - containerPort: 5000
