apiVersion: v1
kind: Service
metadata:
  name: svc-pengedit-md
  labels:
    run: svc-pengedit-md
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    nodePort: 30104
    protocol: TCP
  selector:
    name: pengedit-md
